//
//  TeamRessources.swift
//  FootLeague
//
//  Created by Elliot Knight on 10/11/2022.
//

import Foundation

var teams: [Team] = [
	Team(
		idTeam: nil,
		idSoccerXML: nil,
		idAPIfootball: nil,
		intLoved: nil,
		strTeam: "Ajaccio",
		strTeamShort: nil,
		strAlternate: "AC Ajaccio, Athletic Club Aiaccio",
		strSport: "Soccer",
		strLeague: "French Ligue 1",
		idLeague: "4484",
		strLeague2: "Coupe de France",
		idLeague2: nil,
		strLeague3: nil,
		idLeague3: nil,
		strLeague4: nil,
		idLeague4: nil,
		strLeague5: nil,
		idLeague5: nil,
		strLeague6: nil,
		idLeague6: nil,
		strLeague7: nil,
		idLeague7: nil,
		strKeywords: "L'ACA",
		strStadiumDescription: "Stade François Coty is a football stadium in the Corsican city of Ajaccio, France, and the home of AC Ajaccio. Its capacity is 10,660.\r\n\r\nThe stadium was inaugurated on 1 December 1969 under the name Parc des Sports de l'ACA. A crowd of 14,421 was in attendance to see AC Ajaccio defeat SC Bastia in the Corsican derby. Known informally as Timizzolu, the stadium was renovated in 2002 and renamed after François Coty, a businessman and far-right politician from Ajaccio. Since 2007, the stadium has undergone substantial improvements to enable it to host Ligue 1 matches.",
		strDescriptionEN: "Athletic Club Ajaccio (Corsican: Athletic Club Aiacciu), commonly referred to as AC Ajaccio, ACA or simply Ajaccio, is a French association football club based in the city of Ajaccio on the island of Corsica. The club was founded in 1910 and plays in Ligue 1. The club president is Christian Leca, and the first-team is coached by manager Olivier Pantaloni, following the sacking of Christian Bracconi in October 2014. Ajaccio play their home matches at the Stade François Coty and are rivals with fellow Corsican club Bastia, with whom they contest the Corsica derby (Derby Corse).", strStadiumLocation: "Ajaccio",

		strCountry: "France",
		strTeamBadge: "https://www.thesportsdb.com/images/media/team/badge/qpxvwy1473505505.png",
		strTeamBanner: "https://www.thesportsdb.com/images/media/team/banner/upwrpx1420758932.jpg"),

	Team(
		idTeam: nil,
		idSoccerXML: nil,
		idAPIfootball: nil,
		intLoved: nil,
		strTeam: "Ajaccio",
		strTeamShort: nil,
		strAlternate: "AC Ajaccio, Athletic Club Aiaccio",
		strSport: "Soccer",
		strLeague: "French Ligue 1",
		idLeague: "4484",
		strLeague2: "Coupe de France",
		idLeague2: nil,
		strLeague3: nil,
		idLeague3: nil,
		strLeague4: nil,
		idLeague4: nil,
		strLeague5: nil,
		idLeague5: nil,
		strLeague6: nil,
		idLeague6: nil,
		strLeague7: nil,
		idLeague7: nil,
		strKeywords: "L'ACA",
		strStadiumDescription: "Stade François Coty is a football stadium in the Corsican city of Ajaccio, France, and the home of AC Ajaccio. Its capacity is 10,660.\r\n\r\nThe stadium was inaugurated on 1 December 1969 under the name Parc des Sports de l'ACA. A crowd of 14,421 was in attendance to see AC Ajaccio defeat SC Bastia in the Corsican derby. Known informally as Timizzolu, the stadium was renovated in 2002 and renamed after François Coty, a businessman and far-right politician from Ajaccio. Since 2007, the stadium has undergone substantial improvements to enable it to host Ligue 1 matches.",
		strDescriptionEN: "Athletic Club Ajaccio (Corsican: Athletic Club Aiacciu), commonly referred to as AC Ajaccio, ACA or simply Ajaccio, is a French association football club based in the city of Ajaccio on the island of Corsica. The club was founded in 1910 and plays in Ligue 1. The club president is Christian Leca, and the first-team is coached by manager Olivier Pantaloni, following the sacking of Christian Bracconi in October 2014. Ajaccio play their home matches at the Stade François Coty and are rivals with fellow Corsican club Bastia, with whom they contest the Corsica derby (Derby Corse).",
		strStadiumLocation: "Ajaccio",
		strCountry: "France",
		strTeamBadge: "https://www.thesportsdb.com/images/media/team/badge/qpxvwy1473505505.png",
		strTeamBanner: "https://www.thesportsdb.com/images/media/team/banner/upwrpx1420758932.jpg"),

	Team(
		idTeam: nil,
		idSoccerXML: nil,
		idAPIfootball: nil,
		intLoved: nil,
		strTeam: "Ajaccio",
		strTeamShort: nil,
		strAlternate: "AC Ajaccio, Athletic Club Aiaccio",
		strSport: "Soccer",
		strLeague: "French Ligue 1",
		idLeague: "4484",
		strLeague2: "Coupe de France",
		idLeague2: nil,
		strLeague3: nil,
		idLeague3: nil,
		strLeague4: nil,
		idLeague4: nil,
		strLeague5: nil,
		idLeague5: nil,
		strLeague6: nil,
		idLeague6: nil,
		strLeague7: nil,
		idLeague7: nil,
		strKeywords: "L'ACA",
		strStadiumDescription: "Stade François Coty is a football stadium in the Corsican city of Ajaccio, France, and the home of AC Ajaccio. Its capacity is 10,660.\r\n\r\nThe stadium was inaugurated on 1 December 1969 under the name Parc des Sports de l'ACA. A crowd of 14,421 was in attendance to see AC Ajaccio defeat SC Bastia in the Corsican derby. Known informally as Timizzolu, the stadium was renovated in 2002 and renamed after François Coty, a businessman and far-right politician from Ajaccio. Since 2007, the stadium has undergone substantial improvements to enable it to host Ligue 1 matches.",
		strDescriptionEN: "Athletic Club Ajaccio (Corsican: Athletic Club Aiacciu), commonly referred to as AC Ajaccio, ACA or simply Ajaccio, is a French association football club based in the city of Ajaccio on the island of Corsica. The club was founded in 1910 and plays in Ligue 1. The club president is Christian Leca, and the first-team is coached by manager Olivier Pantaloni, following the sacking of Christian Bracconi in October 2014. Ajaccio play their home matches at the Stade François Coty and are rivals with fellow Corsican club Bastia, with whom they contest the Corsica derby (Derby Corse).",
		strStadiumLocation: "Ajaccio",
		strCountry: "France",
		strTeamBadge: "https://www.thesportsdb.com/images/media/team/badge/qpxvwy1473505505.png",
		strTeamBanner: "https://www.thesportsdb.com/images/media/team/banner/upwrpx1420758932.jpg"),


	Team(
		idTeam: nil,
		idSoccerXML: nil,
		idAPIfootball: nil,
		intLoved: nil,
		strTeam: "Ajaccio",
		strTeamShort: nil,
		strAlternate: "AC Ajaccio, Athletic Club Aiaccio",
		strSport: "Soccer",
		strLeague: "French Ligue 1",
		idLeague: "4484",
		strLeague2: "Coupe de France",
		idLeague2: nil,
		strLeague3: nil,
		idLeague3: nil,
		strLeague4: nil,
		idLeague4: nil,
		strLeague5: nil,
		idLeague5: nil,
		strLeague6: nil,
		idLeague6: nil,
		strLeague7: nil,
		idLeague7: nil,
		strKeywords: "L'ACA",
		strStadiumDescription: "Stade François Coty is a football stadium in the Corsican city of Ajaccio, France, and the home of AC Ajaccio. Its capacity is 10,660.\r\n\r\nThe stadium was inaugurated on 1 December 1969 under the name Parc des Sports de l'ACA. A crowd of 14,421 was in attendance to see AC Ajaccio defeat SC Bastia in the Corsican derby. Known informally as Timizzolu, the stadium was renovated in 2002 and renamed after François Coty, a businessman and far-right politician from Ajaccio. Since 2007, the stadium has undergone substantial improvements to enable it to host Ligue 1 matches.",
		strDescriptionEN: "Athletic Club Ajaccio (Corsican: Athletic Club Aiacciu), commonly referred to as AC Ajaccio, ACA or simply Ajaccio, is a French association football club based in the city of Ajaccio on the island of Corsica. The club was founded in 1910 and plays in Ligue 1. The club president is Christian Leca, and the first-team is coached by manager Olivier Pantaloni, following the sacking of Christian Bracconi in October 2014. Ajaccio play their home matches at the Stade François Coty and are rivals with fellow Corsican club Bastia, with whom they contest the Corsica derby (Derby Corse).",
		strStadiumLocation: "Ajaccio",
		strCountry: "France",
		strTeamBadge: "https://www.thesportsdb.com/images/media/team/badge/qpxvwy1473505505.png",
		strTeamBanner: "https://www.thesportsdb.com/images/media/team/banner/upwrpx1420758932.jpg"),
]


extension Team {
	static let sample = Team(
		idTeam: nil,
		idSoccerXML: nil,
		idAPIfootball: nil,
		intLoved: nil,
		strTeam: "Ajaccio",
		strTeamShort: nil,
		strAlternate: "AC Ajaccio, Athletic Club Aiaccio",
		strSport: "Soccer",
		strLeague: "French Ligue 1",
		idLeague: "4484",
		strLeague2: "Coupe de France",
		idLeague2: nil,
		strLeague3: nil,
		idLeague3: nil,
		strLeague4: nil,
		idLeague4: nil,
		strLeague5: nil,
		idLeague5: nil,
		strLeague6: nil,
		idLeague6: nil,
		strLeague7: nil,
		idLeague7: nil,
		strKeywords: "L'ACA",
		strStadiumDescription: "Stade François Coty is a football stadium in the Corsican city of Ajaccio, France, and the home of AC Ajaccio. Its capacity is 10,660.\r\n\r\nThe stadium was inaugurated on 1 December 1969 under the name Parc des Sports de l'ACA. A crowd of 14,421 was in attendance to see AC Ajaccio defeat SC Bastia in the Corsican derby. Known informally as Timizzolu, the stadium was renovated in 2002 and renamed after François Coty, a businessman and far-right politician from Ajaccio. Since 2007, the stadium has undergone substantial improvements to enable it to host Ligue 1 matches.",
		strDescriptionEN: "Athletic Club Ajaccio (Corsican: Athletic Club Aiacciu), commonly referred to as AC Ajaccio, ACA or simply Ajaccio, is a French association football club based in the city of Ajaccio on the island of Corsica. The club was founded in 1910 and plays in Ligue 1. The club president is Christian Leca, and the first-team is coached by manager Olivier Pantaloni, following the sacking of Christian Bracconi in October 2014. Ajaccio play their home matches at the Stade François Coty and are rivals with fellow Corsican club Bastia, with whom they contest the Corsica derby (Derby Corse).",
		strStadiumLocation: "Ajaccio",
		strCountry: "France",
		strTeamBadge: "https://www.thesportsdb.com/images/media/team/badge/qpxvwy1473505505.png",
		strTeamBanner: "https://www.thesportsdb.com/images/media/team/banner/upwrpx1420758932.jpg")
}
